### ISSUE TITLE
Setup Vercel for Workflow

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Anamaya/workflow#6]
- [x] On every PR
- [x] On every commit

**Comment by geeky-abhishek** [comment]
@amit-s19 https://github.com/Samagra-Anamaya/.github/issues/1

**Comment by geeky-abhishek** [comment]
@amit-s19 to provide the vercel link.

**Comment by amit-s19** [comment]
https://github.com/Samagra-Anamaya/workflow
