### ISSUE TITLE
Create Submission Schema

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Anamaya/workflow#8]

**Comment by geeky-abhishek** [comment]
@ChakshuGautam can you please review this
`

model Submission {
  id                   Int      @id @default(autoincrement())
  submitter            User     @relation(fields: [submitterId], references: [userId])
  submitterId          String
  submissionData       Json
  createdAt            DateTime @default(now())
  updatedAt            DateTime @updatedAt
  verificationIntitaed Boolean  @default(false)
  isUpdated            Boolean @default(false)
  verificationDate     DateTime
  isVerified           Boolean  @default(false)
  errors               Json?
}

model User {
  id          Int          @id @default(autoincrement())
  userId      String       @unique
  submissions Submission[]
  mobile      String
  active      Boolean @default(true)
  surveyAssigned Int @default(0)
  surveyCompleted Int @default(0)
}

`
