### ISSUE TITLE
Server Details

### ISSUE THREAD

**Issue by geeky-abhishek** [Samagra-Anamaya/workflow#89]

**Comment by singhalkarun** [comment]
**A. IP:- 10.150.220.198**

Working
Disk 1: 40 GB
Disk 2: 230 GB
Memory: 16 GB
Cores: 4
OS: Ubuntu 20.04.6

**B. IP:- 10.150.220.199**

VM Password Shows Invalid

**C. IP:- 10.150.220.200**

Working
Disk 1: 40 GB
Disk 2: 230 GB
Memory: 16 GB
Cores: 8
OS: Ubuntu 20.04.6 LTS

**D. IP:- 10.150.220.201**

Working
Disk 1: 40 GB
Disk 2: 230 GB
Memory: 16 GB
Cores: 8
OS: Ubuntu 20.04.6 LTS

**E. VPN: Working**

**F. FTP:  Working**

*Note: I am yet to verify DB Credentials and details. ```psql``` client is not available in VMs so not able to verify yet. I will update on this soon.*
